package com.juren233.easyopen.shared.resources

/**
 * Literal strings used by the iOS fallback resolver.
 *
 * Compose Multiplatform Resources currently produces correct CVR bytes in the
 * build, but the affected iOS build returned corrupted static resource text at
 * runtime while dynamic Kotlin strings remained correct. Keep this generated
 * table in common code so iOS can bypass that failing read path without
 * changing Android resource behavior.
 *
 * The table is generated from shared/src/commonMain/composeResources/values/strings.xml.
 */
internal val easyOpenStringValues: Map<String, String> = mapOf(
    "add_opener_title" to "添加开门器",
    "configure_opener_title" to "设置开门器",
    "pair_opener_section" to "配对开门器",
    "imported_opener_profile" to "待绑定的导入配置",
    "add_another_opener_section" to "添加另一台开门器",
    "search_nearby_openers" to "搜索附近的开门器",
    "pairing_password_in_progress" to "正在验证密码，请保持开门器在附近",
    "searching" to "搜索中...",
    "keep_opener_powered_nearby" to "请让开门器保持通电，并靠近手机",
    "found_openers" to "找到 %1\$d 台可配对的开门器",
    "open_bluetooth_settings" to "打开蓝牙设置",
    "search_again" to "重新搜索",
    "start_search" to "开始搜索",
    "search_results" to "搜索结果",
    "saved_openers" to "已保存的开门器",
    "saved_opener_summary" to "%1\$s",
    "scan_import_title" to "扫码添加开门器",
    "no_opener_found" to "暂未找到开门器",
    "no_opener_found_summary" to "请检查开门器是否通电后再试",
    "device_signal_summary" to "%1\$s · %2\$d dBm",
    "password_dialog_title" to "输入开门器密码",
    "password_dialog_description" to "请输入 %1\$s 的 6 位数字密码。验证只会执行配对初始化，不会发送开门指令。",
    "password_field_label" to "6 位数字密码",
    "verify_and_pair" to "验证并配对",
    "verifying" to "验证中...",
    "discard_settings_title" to "放弃当前设置？",
    "discard_settings_message" to "返回第一页会丢失当前设置，是否继续？",
    "pairing_flow_page_transition" to "配对流程页面切换",
    "opener_name_optional" to "开门器名称（可选）",
    "opener_name" to "开门器名称",
    "home_title" to "EasyOpen",
    "update_available_notice" to "发现新版本 %1\$s，点击查看更新",
    "status_connected" to "已连接",
    "status_connecting" to "连接中",
    "status_discovered" to "已发现",
    "status_not_found" to "未发现",
    "device_summary" to "%1\$s\n%2\$s · %3\$s",
    "switch_opener" to "切换",
    "one_tap_unlock" to "一键开门",
    "opener_settings_collapsed" to "开门器设置",
    "opener_settings_expanded" to "收起开门器设置",
    "password_field_settings" to "开门器密码（6 位数字）",
    "share_opener_title" to "分享开门器",
    "switch_opener_dialog_title" to "切换开门器",
    "current_device_summary" to "%1\$s · 当前",
    "add_opener_dialog_summary" to "搜索并配对另一台开门器",
    "select_all" to "全选",
    "generate_share_qr" to "生成分享二维码",
    "nfc_write_title" to "写入NFC标签",
    "nfc_read_title" to "读取NFC并开门",
    "lock_direction" to "拉锁方向",
    "forward" to "正向",
    "reverse" to "反向",
    "open_duration" to "开启 ms",
    "hold_duration" to "保持 ms",
    "close_duration" to "关闭 ms",
    "complete_pairing" to "完成配对",
    "battery_low" to "电量低",
    "battery_25" to "电量约 25%",
    "battery_50" to "电量约 50%",
    "battery_75" to "电量约 75%",
    "battery_100" to "电量约 100%",
    "battery_unknown" to "电量未知",
    "automation_category" to "自动化",
    "auto_connect_range_near" to "靠近",
    "auto_connect_range_moderate" to "适中",
    "auto_connect_range_far" to "远距离",
    "auto_connect_range_custom" to "自定义",
    "auto_connect_opener" to "自动连接开门器",
    "auto_unlock_on_app_open" to "进入 App 自动开门",
    "auto_connect_range" to "自动连接范围",
    "auto_connect_signal_value" to "自动连接信号值",
    "auto_connect_signal_value_format" to "-%1\$d dBm",
    "auto_connect_signal_value_input" to "输入信号值（1-127）",
    "auto_connect_signal_value_invalid" to "请输入 1 到 127 之间的数字",
    "cancel" to "取消",
    "continue_action" to "继续",
    "save_settings" to "保存设置",
    "settings_title" to "设置",
    "back" to "返回",
    "personalization_category" to "个性化",
    "theme_color_title" to "主题颜色",
    "theme_system" to "系统",
    "theme_light" to "浅色",
    "theme_dark" to "深色",
    "monet_color_title" to "莫奈取色",
    "data_category" to "数据",
    "backup_title" to "备份",
    "restore_title" to "恢复",
    "app_name" to "EasyOpen",
    "first_use" to "首次使用",
    "bluetooth_permission_title" to "需要蓝牙与定位权限",
    "bluetooth_permission_summary" to "用于搜索附近的 YILA 开门器，并与已配对的开门器建立连接。部分手机系统会将蓝牙扫描与定位权限关联，首次使用时可能会同时请求定位权限。",
    "grant_permission" to "授予权限",
    "default_opener_advertised_name" to "YILA 开门器",
    "status_disconnected" to "未连接",
    "error_bluetooth_permission" to "请先授予蓝牙扫描和连接权限",
    "error_bluetooth_disabled" to "请先打开手机蓝牙",
    "error_scanner_unavailable" to "蓝牙扫描器不可用",
    "error_scan_failed" to "扫描失败：错误码 %1\$d",
    "error_scan_start_failed" to "启动扫描失败：%1\$s",
    "error_unknown" to "未知错误",
    "error_password_length" to "开门器密码必须是 6 位数字",
    "error_password_not_configured" to "请先配置开门器密码",
    "error_address_invalid" to "蓝牙地址格式不正确",
    "error_device_not_found" to "找不到设备 %1\$s",
    "error_pairing_connection_lost" to "配对失败：蓝牙连接中断（状态码 %1\$d），请确认开门器在附近后重试",
    "error_unlock_connection_lost" to "开门失败：蓝牙连接中断（状态码 %1\$d）",
    "error_pairing_timeout" to "配对失败：开门器在 13 秒内未确认密码，请确认设备在附近后重试",
    "error_unlock_timeout" to "开门失败：设备在规定时间内没有响应，请重试",
    "error_pairing_write_status" to "配对失败：蓝牙写入队列繁忙（状态码 %1\$d），请稍后重试",
    "error_unlock_write_status" to "开门失败：写入命令失败，状态码 %1\$d",
    "error_pairing_write_exception" to "配对失败：发送密码初始化命令异常（%1\$s）",
    "error_unlock_write_exception" to "开门失败：写入命令异常（%1\$s）",
    "error_unlock_parameter_invalid" to "开门参数无效",
    "error_connection_lost" to "蓝牙连接断开：状态码 %1\$d",
    "error_connection_timeout" to "连接开门器超时，请靠近开门器后重试",
    "error_pairing_connection_timeout" to "配对失败：连接开门器超时，请确认设备在附近后重试",
    "error_pairing_services_failed" to "配对失败：发现开门器服务失败（状态码 %1\$d）",
    "error_services_failed" to "发现服务失败：状态码 %1\$d",
    "error_pairing_service_missing" to "配对失败：未找到开门器通信服务",
    "error_service_missing" to "未找到开门器通信服务",
    "error_pairing_notifications_failed" to "配对失败：启用开门器通知失败",
    "error_notifications_failed" to "启用开门器通知失败",
    "error_pairing_service_not_ready" to "配对失败：开门器通信服务尚未就绪，请重新选择设备后重试",
    "error_unlock_service_not_ready" to "开门失败：开门器通信服务尚未就绪",
    "error_invalid_password_parameter" to "密码参数无效",
    "error_pairing_write_busy" to "配对失败：蓝牙写入队列持续繁忙，请重新选择开门器后重试",
    "error_unlock_write_busy" to "开门失败：蓝牙写入队列持续繁忙，请重试",
    "error_pairing_notification_busy" to "配对失败：开门器通知通道持续繁忙，无法开始验证密码",
    "error_unlock_notification_busy" to "开门失败：开门器通知通道持续繁忙，请重试",
    "error_pairing_password_wrong" to "配对失败：密码错误，请确认是开门器的 6 位数字密码",
    "error_pairing_unknown_response" to "配对失败：开门器返回未识别响应（%1\$s）",
    "unlock_success" to "开门成功 · %1\$s",
    "error_opener_response" to "开门器返回：%1\$s",
    "share_qr_title" to "分享二维码",
    "share_qr_content_description" to "开门器设置分享二维码",
    "share_qr_summary" to "已包含 %1\$d 台开门器设置。二维码包含开门器密码，请仅分享给可信的人。",
    "close" to "关闭",
    "scan_from_gallery" to "从相册选择二维码",
    "rescan_qr" to "重新扫码",
    "rescan_from_gallery" to "重新从相册选择二维码",
    "restore_backup_file" to "恢复备份文件",
    "rescan_backup_file" to "重新恢复备份文件",
    "scan_import_decoding" to "正在识别二维码",
    "camera_permission_required" to "需要相机权限才能扫描二维码",
    "allow_camera" to "允许相机权限",
    "camera_start_failed" to "相机启动失败，请重试",
    "retry" to "重试",
    "qr_import_invalid" to "无法识别有效的 EasyOpen 分享二维码，请重试。",
    "qr_import_found" to "发现 %1\$d 台开门器",
    "backup_found" to "发现备份：%1\$d 台开门器",
    "import_opener" to "导入开门器",
    "restore_backup" to "恢复备份",
    "nfc_dispatch_permission" to "",
    "nfc_write_waiting_title" to "等待 NFC 标签",
    "nfc_write_waiting_description" to "请将手机靠近要写入的 NFC 标签。读取完成后，你可以选择是否保留标签原有内容。",
    "nfc_write_choice_title" to "保留原 NFC 内容？",
    "nfc_write_choice_description" to "检测到标签中已有 %1\$d 条 NDEF 记录。是否保留原内容并加入 EasyOpen 开门内容？",
    "nfc_write_choice_empty" to "未检测到标签原有内容，将直接写入 EasyOpen 开门内容。",
    "nfc_write_without_original" to "不保留，直接写入",
    "nfc_write_preserve_original" to "保留并合并",
    "nfc_write_reconnect_title" to "重新贴近 NFC 标签",
    "nfc_write_reconnect_description" to "写入选项已确认。请先移开手机，再重新贴近要写入的 NFC 标签；检测到后将立即写入，请保持贴近直到完成。",
    "nfc_write_in_progress_title" to "正在写入 NFC 标签",
    "nfc_write_in_progress_description" to "请保持手机靠近 NFC 标签，写入完成前不要移开。",
    "nfc_write_success" to "NFC 标签写入成功，现在可以碰一碰自动开门",
    "nfc_write_failed" to "NFC 标签写入失败：%1\$s",
    "nfc_write_failed_unknown" to "未知错误",
    "nfc_not_supported" to "当前设备不支持 NFC",
    "nfc_turn_on" to "请先打开系统 NFC",
    "backup_success" to "备份成功",
    "backup_failed" to "备份失败",
    "restore_success" to "恢复成功",
    "restore_failed" to "恢复失败，文件格式无效",
)

private val easyOpenStringArgumentPattern = Regex("""%(\d+)\$[ds]""")

internal fun String.replaceEasyOpenStringArguments(arguments: Array<out Any>): String =
    easyOpenStringArgumentPattern.replace(this) { match ->
        arguments.getOrNull(match.groupValues[1].toInt() - 1)?.toString() ?: match.value
    }
